/*
 * File: app/view/Conditions.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HooferSailingMobile.view.Conditions', {
    extend: 'Ext.Container',
    alias: 'widget.conditions',

    requires: [
        'HooferSailingMobile.view.RotatingImage',
        'Ext.Component',
        'Ext.XTemplate'
    ],

    config: {
        layout: {
            type: 'vbox',
            pack: 'center'
        },
        items: [
            {
                xtype: 'rotatingimage'
            },
            {
                xtype: 'component',
                tpl: [
                    '<p style="text-align:center;margin-top:0em;font-size:3em;">',
                    '    <b>{knots}</b> kn',
                    '</p>',
                    '',
                    '<p style="text-align:center;font-size:1.5em;">',
                    '{gusts} kn gusts',
                    '</p>',
                    '',
                    '<p style="margin-top:.3em;text-align:center;font-size: 1.5em;">',
                    'Water temp. {waterTemperature}&deg;F',
                    '</p>'
                ]
            },
            {
                xtype: 'component',
                tpl: [
                    '<tpl if="color">',
                    '<img src="resources/images/Flags/{color}.png" />',
                    '</tpl>'
                ]
            }
        ]
    }

});