/*
 * File: app/view/MyCarousel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HooferSailingMobile.view.MyCarousel', {
    extend: 'Ext.carousel.Carousel',

    requires: [
        'HooferSailingMobile.view.Conditions',
        'HooferSailingMobile.view.Boats',
        'Ext.navigation.View',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    config: {
        indicator: false,
        items: [
            {
                xtype: 'conditions'
            },
            {
                xtype: 'boats'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                layout: {
                    type: 'hbox',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'button',
                        iconCls: 'flag',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        ui: 'plain',
                        iconCls: 'anchor',
                        text: ''
                    }
                ]
            }
        ]
    }

});